sonar.projectKey=Nuagrinn_go-project-278
sonar.projectName=go-project-278
sonar.organization=nuagrinn
sonar.host.url=https://sonarcloud.io

sonar.sources=.
sonar.exclusions=internal/db/**,node_modules/**,.cache/**,.gomodcache/**,.npm-cache/**,bin/**,code,coverage.out

sonar.tests=.
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage.out
sonar.coverage.exclusions=**/*_test.go,internal/db/**,main.go,postgres_store.go
sonar.qualitygate.wait=true
